# These configs ensure docs are processed by Jekyll
# Be aware this slows down the build process
# Add this file to the serve command to enable docs

defaults:
  -
    scope:
      path: "docs/envoy"
    values:
      render_with_liquid: false

exclude:
  - envoy-source/

include:
  - _downloads
  - _images
  - _include
  - _sources
  - _static

keep_files:
  - docs/envoy
