services:
  envoy-site:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - envoy_source:/home/builder/envoy
      - envoy_archive:/home/builder/envoy-archive
      - builder_tools:/home/builder/tools
      - builder_metadata:/home/builder/metadata
      - jekyll_output:/home/builder/output
      - jekyll_source:/home/builder/app
      - .:/home/builder/envoy-site
    ports:
      - "8089:4000"
    environment:
      - BUILD_DOCS=false
    platform: linux/amd64
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: '4G'
        reservations:
          cpus: '1.0'
          memory: '2G'

  file-sync:
    image: alpine:latest
    volumes:
      - .:/home/builder/envoy-site
      - jekyll_source:/home/builder/app
    entrypoint: >
      sh -c "
      apk add --no-cache inotify-tools rsync &&
      while true; do
        inotifywait -r -e modify,create,delete,move --exclude '\.git|\.DS_Store' /home/builder/envoy-site &&
        rsync -a --info=progress2 --no-perms --no-owner --no-group --delete --exclude='docs' --exclude='_site' --exclude='.DS_Store' --exclude='.git' --exclude='.gitignore' --exclude='build_docs.sh' --exclude='scripts/**' --exclude='Dockerfile' --exclude='docker-compose.yml' --exclude='README.md'  --exclude='.dockerignore'  /home/builder/envoy-site/ /home/builder/app/
      done
      "

volumes:
  builder_tools:
  envoy_source:
  envoy_archive:
  builder_metadata:
  jekyll_output:
  jekyll_source:
