name: ci

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export
        uses: docker/build-push-action@v6
        with:
          file: ./build/base.Dockerfile
          tags: envoy-site-base:latest
          outputs: type=docker,dest=/tmp/envoy-site-base.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: envoy-site-base
          path: /tmp/envoy-site-base.tar

  use:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: envoy-site-base
          path: /tmp

      - name: Load image
        run: |
          docker load --input /tmp/envoy-site-base.tar
          docker image ls -a

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export
        uses: docker/build-push-action@v6
        with:
          file: ./build/build-github.Dockerfile
          tags: envoy-site-build:latest
          outputs: type=docker,dest=/tmp/envoy-site-build.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: envoy-site-build
          path: /tmp/envoy-site-build.tar
